version: '3.7'
services: # 이 항목 밑에 실행하려는 컨테이너 들을 정의
  prometheus: # 서비스 명
    image: prom/prometheus:latest # 사용할 이미지
    container_name: prometheus # 컨테이너 이름 설정
    user: "root"
    ports:
      - 9090:9090
    volumes:
      - ~/prometheus/config/:/etc/prometheus/
      - ~/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "root"
    ports:
      - 3000:3000
    volumes:
      - ~/grafana/config/grafana.ini:/etc/grafana/grafana.ini'
      - ~/grafana/data:/var/lib/grafana
    restart: always
    depends_on:
      - prometheus
